# Generated by Django 5.2.17 on 2026-10-04 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalMidia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='nome')),
                ('root_path', models.CharField(max_length=1000, verbose_name='raiz absoluta no servidor')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'local de mídia',
                'verbose_name_plural': 'locais de mídia',
                'ordering': ['name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nome de exibição')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
            ],
            options={
                'verbose_name': 'pessoa',
                'ordering': ['name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('normalized_name', models.CharField(editable=False, max_length=300, unique=True)),
                ('color', models.CharField(blank=True, max_length=7, verbose_name='cor')),
            ],
            options={
                'ordering': ['normalized_name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('relative_path', models.CharField(max_length=1000, verbose_name='caminho relativo')),
                ('path_key', models.CharField(editable=False, max_length=1000)),
                ('duration_ms', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='duração em milissegundos')),
                ('file_status', models.CharField(choices=[('available', 'Arquivo disponível'), ('missing', 'Arquivo não encontrado'), ('unreadable', 'Sem acesso ao arquivo')], default='missing', editable=False, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_videos', to=settings.AUTH_USER_MODEL)),
                ('local_midia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.localmidia', verbose_name='local de mídia')),
                ('people', models.ManyToManyField(blank=True, related_name='videos', to='catalog.pessoa', verbose_name='pessoas')),
                ('tags', models.ManyToManyField(blank=True, related_name='videos', to='catalog.tag')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'vídeo',
                'ordering': ['-updated_at', '-pk'],
                'constraints': [models.UniqueConstraint(fields=('local_midia', 'path_key'), name='unique_video_media_reference')],
            },
        ),
    ]
