# Generated by Django 5.2.17 on 2026-10-04 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='codec',
            field=models.CharField(blank=True, editable=False, max_length=80),
        ),
        migrations.AddField(
            model_name='video',
            name='duration_source',
            field=models.CharField(choices=[('unknown', 'Desconhecida'), ('automatic', 'Extraída'), ('manual', 'Manual')], default='unknown', editable=False, max_length=10),
        ),
        migrations.AddField(
            model_name='video',
            name='height',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='inspected_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='inspection_message',
            field=models.CharField(blank=True, editable=False, max_length=250),
        ),
        migrations.AddField(
            model_name='video',
            name='inspection_status',
            field=models.CharField(choices=[('pending', 'Não inspecionado'), ('ready', 'Inspecionado'), ('failed', 'Falha de inspeção'), ('unavailable', 'Inspeção indisponível')], default='pending', editable=False, max_length=12),
        ),
        migrations.AddField(
            model_name='video',
            name='size_bytes',
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail_key',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail_relative_path',
            field=models.CharField(blank=True, max_length=1000, verbose_name='miniatura manual: caminho relativo'),
        ),
        migrations.AddField(
            model_name='video',
            name='width',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
