# Generated by Django 5.2.17 on 2026-10-05 00:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_video_codec_video_duration_source_video_height_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarcacaoTemporal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('start_ms', models.PositiveBigIntegerField(verbose_name='início em milissegundos')),
                ('end_ms', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='fim em milissegundos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_markings', to=settings.AUTH_USER_MODEL)),
                ('people', models.ManyToManyField(blank=True, related_name='markings', to='catalog.pessoa', verbose_name='pessoas')),
                ('tags', models.ManyToManyField(blank=True, related_name='markings', to='catalog.tag')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_markings', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markings', to='catalog.video')),
            ],
            options={
                'verbose_name': 'marcação temporal',
                'verbose_name_plural': 'marcações temporais',
                'ordering': ['start_ms', 'pk'],
                'indexes': [models.Index(fields=['video', 'start_ms'], name='annotations_video_i_8708ea_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_ms__isnull', True), ('end_ms__gte', models.F('start_ms')), _connector='OR'), name='marking_end_not_before_start')],
            },
        ),
    ]
