# Generated by Django 5.2.17 on 2026-10-05 01:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0001_initial'),
        ('catalog', '0002_video_codec_video_duration_source_video_height_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubtitleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nome da versão')),
                ('language', models.CharField(blank=True, max_length=40, verbose_name='idioma (opcional)')),
                ('active', models.BooleanField(default=False)),
                ('source', models.CharField(default='srt', editable=False, max_length=20, verbose_name='origem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitle_versions', to='catalog.video')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='SubtitleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_ms', models.PositiveBigIntegerField(verbose_name='início')),
                ('end_ms', models.PositiveBigIntegerField(verbose_name='fim')),
                ('text', models.TextField(max_length=10000, verbose_name='texto')),
                ('order', models.PositiveIntegerField(default=0, editable=False)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='annotations.subtitleversion')),
            ],
            options={
                'ordering': ['start_ms', 'order', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='subtitleversion',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('video',), name='one_active_subtitle_version'),
        ),
        migrations.AddConstraint(
            model_name='subtitleentry',
            constraint=models.CheckConstraint(condition=models.Q(('end_ms__gt', models.F('start_ms'))), name='subtitle_end_after_start'),
        ),
    ]
